name: 🚀 Give Strava Kudos

on:
  # Triggers every 9:30am
  schedule:
    - cron: "30 9 * * *"
  workflow_dispatch:

env:
  STRAVA_EMAIL: ${{ secrets.STRAVA_EMAIL }}
  STRAVA_PASSWORD: ${{ secrets.STRAVA_PASSWORD }}
  API_TOKEN: ${{ secrets.API_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}
jobs:
  run-kudos-cron:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3 
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7.6'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: playwright install
      - run: python give_kudos.py
